name: Build Qlang binaries
on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - ubuntu
          - windows 
          - macos
        include:
          - os: windows 
            ext: .exe
    steps:
      - uses: actions/checkout@v3
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-13.0
      - name: Install LLVM and Clang 
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit || (matrix.os == "windows") }}
      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with: 
          path: target 
          key: cargo_deps-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - name: Build Qlang 
        run: | 
          cargo b --release
          mv target/release/qlang ${{ matrix.os }}${{ matrix.ext }}
      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: ${{ matrix.os }}${{ matrix.ext }}
