name: Lint
on: [push]

jobs:
  Lint:
    name: Lint code with Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm 
          key: llvm-13.0
      - name: Install LLVM and Clang 
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with: 
          path: target 
          key: | 
            cargo_deps-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}   
            cargo_deps-${{ runner.os }}- 
            cargo_deps-
      - name: Run Clippy
        run: cargo clippy
