name: Lint
on: [push]

jobs:
  Lint:
    name: Lint code with Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3 
        with: 
          path: target/deps 
          key: depcache-${{ runner.os }}-${{ hashFiles('Cargo.lock') }} 
          restore-keys: |
            depcache-${{ runner.os }}-
            depcache-
      - name: Run Clippy
        run: cargo clippy
