name: Lint
on:
  push:
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  Lint:
    name: Lint code with Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm 
          key: llvm-13.0
      - name: Install LLVM and Clang 
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit || (matrix.os == "windows") }}
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with: 
          path: target 
          key: cargo_deps-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - name: Run Clippy
        run: "cargo clippy"
